import {
  DEMO_DATE,
  type AppState,
  type Demonstration,
  type Reservation,
} from "./domain";

export const reservationFixtures: Reservation[] = [
  {
    id: "R-2041",
    guestDisplayName: "Aiko Tanaka",
    status: "confirmed",
    arrivalDate: DEMO_DATE,
    plannedArrivalTime: "18:00",
    requestedArrivalTime: "21:30",
    estimatedArrivalTime: "21:30",
    mealPlan: "dinner_included",
    mealService: "late_meal_box",
    hasNewDietaryRequest: false,
    dietaryRequestHandled: false,
    requestsTaxi: false,
    taxiArranged: false,
    requestsCompensation: false,
    guestMessageDraft: "Your late-arrival meal box will be ready at reception.",
    shiftHandoff: "Late arrival at 21:30. Meal box at reception.",
    version: 2,
  },
  {
    id: "R-2048",
    guestDisplayName: "Emma Wilson",
    status: "confirmed",
    arrivalDate: DEMO_DATE,
    plannedArrivalTime: "17:30",
    requestedArrivalTime: "20:45",
    estimatedArrivalTime: null,
    mealPlan: "dinner_included",
    mealService: "regular_dinner",
    hasNewDietaryRequest: false,
    dietaryRequestHandled: false,
    requestsTaxi: false,
    taxiArranged: false,
    requestsCompensation: false,
    guestMessageDraft: null,
    shiftHandoff: null,
    version: 1,
  },
  {
    id: "R-2050",
    guestDisplayName: "Sofia Rossi",
    status: "confirmed",
    arrivalDate: DEMO_DATE,
    plannedArrivalTime: "18:15",
    requestedArrivalTime: "23:30",
    estimatedArrivalTime: "23:30",
    mealPlan: "dinner_included",
    mealService: "late_meal_box",
    hasNewDietaryRequest: true,
    dietaryRequestHandled: true,
    requestsTaxi: true,
    taxiArranged: true,
    requestsCompensation: false,
    guestMessageDraft:
      "Your dietary-safe meal box and taxi are arranged for your late arrival.",
    shiftHandoff:
      "Night arrival at 23:30. Dietary-safe meal box and taxi arranged.",
    version: 2,
  },
  {
    id: "R-2052",
    guestDisplayName: "Daniel Kim",
    status: "confirmed",
    arrivalDate: DEMO_DATE,
    plannedArrivalTime: "18:30",
    requestedArrivalTime: "23:40",
    estimatedArrivalTime: null,
    mealPlan: "dinner_included",
    mealService: "regular_dinner",
    hasNewDietaryRequest: true,
    dietaryRequestHandled: false,
    requestsTaxi: true,
    taxiArranged: false,
    requestsCompensation: false,
    guestMessageDraft: null,
    shiftHandoff: null,
    version: 1,
  },
  {
    id: "R-2054",
    guestDisplayName: "Maya Patel",
    status: "confirmed",
    arrivalDate: DEMO_DATE,
    plannedArrivalTime: "18:45",
    requestedArrivalTime: "21:45",
    estimatedArrivalTime: null,
    mealPlan: "dinner_included",
    mealService: "regular_dinner",
    hasNewDietaryRequest: false,
    dietaryRequestHandled: false,
    requestsTaxi: false,
    taxiArranged: false,
    requestsCompensation: false,
    guestMessageDraft: null,
    shiftHandoff: null,
    version: 1,
  },
  {
    id: "R-2056",
    guestDisplayName: "Lucas Meyer",
    status: "confirmed",
    arrivalDate: DEMO_DATE,
    plannedArrivalTime: "18:10",
    requestedArrivalTime: "22:50",
    estimatedArrivalTime: null,
    mealPlan: "dinner_included",
    mealService: "regular_dinner",
    hasNewDietaryRequest: true,
    dietaryRequestHandled: false,
    requestsTaxi: true,
    taxiArranged: false,
    requestsCompensation: false,
    guestMessageDraft: null,
    shiftHandoff: null,
    version: 1,
  },
  {
    id: "R-2058",
    guestDisplayName: "Priya Shah",
    status: "confirmed",
    arrivalDate: DEMO_DATE,
    plannedArrivalTime: "19:00",
    requestedArrivalTime: "00:20",
    estimatedArrivalTime: null,
    mealPlan: "room_only",
    mealService: "none",
    hasNewDietaryRequest: false,
    dietaryRequestHandled: false,
    requestsTaxi: false,
    taxiArranged: false,
    requestsCompensation: false,
    guestMessageDraft: null,
    shiftHandoff: null,
    version: 1,
  },
  {
    id: "R-2060",
    guestDisplayName: "Noah Martin",
    status: "confirmed",
    arrivalDate: DEMO_DATE,
    plannedArrivalTime: "17:45",
    requestedArrivalTime: "21:15",
    estimatedArrivalTime: null,
    mealPlan: "dinner_included",
    mealService: "regular_dinner",
    hasNewDietaryRequest: false,
    dietaryRequestHandled: false,
    requestsTaxi: false,
    taxiArranged: false,
    requestsCompensation: true,
    guestMessageDraft: null,
    shiftHandoff: null,
    version: 1,
  },
];

export const demonstrationFixtures: Demonstration[] = [
  {
    id: "demo-late-arrival-aiko",
    reservationId: "R-2041",
    playbookId: "late-arrival-care@1",
    capturedAt: "2026-08-27T09:00:00.000Z",
    actions: [
      { type: "set_estimated_arrival", from: "requestedArrivalTime" },
      { type: "set_meal_service", value: "late_meal_box" },
      { type: "draft_guest_message", template: "late_arrival" },
      { type: "add_shift_handoff", template: "late_arrival" },
    ],
  },
  {
    id: "demo-night-arrival-sofia",
    reservationId: "R-2050",
    playbookId: "night-arrival-coordination@1",
    capturedAt: "2026-08-27T09:10:00.000Z",
    actions: [
      { type: "set_estimated_arrival", from: "requestedArrivalTime" },
      { type: "set_meal_service", value: "late_meal_box" },
      { type: "handle_dietary_request" },
      { type: "arrange_taxi" },
      { type: "draft_guest_message", template: "night_arrival" },
      { type: "add_shift_handoff", template: "night_arrival" },
    ],
  },
];

export function createInitialState(): AppState {
  return {
    storageVersion: 3,
    reservations: structuredClone(reservationFixtures),
    selectedReservationId: "R-2048",
    runsByReservationId: {},
    rejectionsByReservationId: {},
    audit: [
      {
        id: "audit-seed",
        at: "2026-08-27T09:00:00.000Z",
        actor: "Human",
        summary: "Recorded the Late Arrival Care demonstration on R-2041.",
      },
    ],
  };
}
